on: push
name: Build & Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
      - name: Upload resume as artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf